# Generated by Django 6.0 on 2026-02-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catalog_options_product_catalog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['-created_at'], 'permissions': [('can_unpublish_product', 'Может отменять публикацию продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
